name: class_match_file_name
description: A linter to ensure that class name matches file name.
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4
