name: class_match_file_name
description: "Linter rule to ensure that the class name matches the file name."
version: 0.0.2
repository: https://github.com/valeriiaradzivilo/class_match_file_name

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  custom_lint_core: ^0.6.3
  custom_lint_builder: ^0.6.4
  test: ^1.25.2

flutter:
