name: class_match_file_name
description: A linter to ensure that class name matches file name. For example if file name is `my_class.dart` then class name should be `MyClass`. Created by Ukrainian
version: 0.2.2
repository: https://github.com/valeriiaradzivilo/class_match_file_name.git

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
