name: class_match_file_name
description: A linter to ensure that class name matches file name. For example if file name is `my_class.dart` then class name should be `MyClass`. Created by Ukrainian 🇺🇦
version: 0.1.2
repository: https://github.com/valeriiaradzivilo/class_match_file_name.git

environment:
  sdk: ^3.3.4

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4
